### ISSUE TITLE
PaddleOCR compiled with CUDA 12.8 in latest v1.3.1 release not compatible with 10 series GPUs

### ISSUE THREAD

**Issue by anhducxz** [timminator/VideOCR#36]
[2025-08-21 12:11:12] PaddleOCR process failed with exit code 1.
Command: D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr.exe ocr --input C:\Users\Windows\AppData\Local\Temp\videocr_temp_sr05qh70 --device gpu --use_textline_orientation false --use_doc_orientation_classify False --use_doc_unwarping False --lang chinese_cht --text_detection_model_dir D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR.PP-OCRv5.support.files\det\PP-OCRv5_mobile_det --text_detection_model_name PP-OCRv5_mobile_det --text_recognition_model_dir D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR.PP-OCRv5.support.files\rec\PP-OCRv5_mobile_rec --text_recognition_model_name PP-OCRv5_mobile_rec

--- STDOUT ---

--- STDERR ---
D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\_utils\cli.py:95: UserWarning: `lang` and `ocr_version` will be ignored when model names or model directories are not `None`.
[32mCreating model: ('PP-OCRv5_mobile_det', 'D:\\Program Files\\VideOCR\\videocr-cli-GPU-v1.3.1\\PaddleOCR.PP-OCRv5.support.files\\det\\PP-OCRv5_mobile_det')[0m
[32mCreating model: ('PP-OCRv5_mobile_rec', 'D:\\Program Files\\VideOCR\\videocr-cli-GPU-v1.3.1\\PaddleOCR.PP-OCRv5.support.files\\rec\\PP-OCRv5_mobile_rec')[0m
Traceback (most recent call last):
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\wrapper.py", line 36, in <module>
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\__main__.py", line 26, in console_entry
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\_cli.py", line 126, in main
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\_cli.py", line 115, in _execute
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\_pipelines\ocr.py", line 630, in execute_with_args
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddleocr\_utils\cli.py", line 110, in perform_simple_inference_ocr
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\pipelines\_parallel.py", line 129, in predict
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\pipelines\ocr\pipeline.py", line 350, in predict
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\models\base\predictor\base_predictor.py", line 211, in __call__
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\models\base\predictor\base_predictor.py", line 267, in apply
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\models\text_detection\predictor.py", line 105, in process
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\models\common\static_infer.py", line 287, in __call__
  File "D:\Program Files\VideOCR\videocr-cli-GPU-v1.3.1\PaddleOCR-GPU-v1.3.0-CUDA-12.8\paddlex\inference\models\common\static_infer.py", line 252, in __call__
OSError: In user code:

    ExternalError: CUDNN error(5000), CUDNN_STATUS_EXECUTION_FAILED. 
      [Hint: Please search for the error code(5000) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at D:\Users\Tim\Downloads\Paddle_compile\Paddle\paddle\phi\kernels\fusion\gpu\fused_conv2d_add_act_kernel.cu:584)
      [operator < pd_kernel.phi_kernel > error]

**Comment by timminator** [comment]
What's your GPU model?
Can you try out the GPU version of my previous 1.3.0 release as well please?

**Comment by anhducxz** [comment]
I use gtx 1070. It support?

**Comment by timminator** [comment]
Thanks for the Video. That was perfect to troubleshoot the issue you are facing. I was able to fix it. I made a new Beta you can find it here:
https://github.com/timminator/VideOCR/releases/download/v1.3.1/VideOCR-CPU-v1.3.2-Beta.7z
Currently CPU only because I need to figure out how to handle the 10 Series GPU compatibility issue first. Please try it out and tell me if it works.

**Comment by anhducxz** [comment]
It worked but I think you should check out videosubfinder . the way they only created 60 images / video I shared. (about 30s running) and I combined with paddle v5 it only took about 15s to create the finished product

**Comment by timminator** [comment]
I know about videosubfinder. But I also had quite a few issues with it. I was not really happy with it. You can of course use it if it works well for you.

**Comment by anhducxz** [comment]
You can give less frames to speed up the process.

**Comment by timminator** [comment]
My program works fundamentally different than VideoSubFinder - I cannot simple give less frames to the PaddleOCR engine - the accuracy of the subtitle detection would drop quite a lot.
You can reduce the number of images used for the OCR process via the SSIM Threshold in the advanced settings. You can lower it for example to something like 80 if your crop box is relatively tight around the hardcoded subtitles.
But your video has quite a few changes "behind" the text so the image count stays relatively high.
My tool definitely performs the OCR process on more images, but the timing and detection accurary of the subs works better for me with my tool than when I used VideoSubFinder before.
But thats just my experience - feel free to use what you want.

**Comment by timminator** [comment]
> might need to make a modified version of paddle for your program

@techguru0 What are you referring to? The main issue of this thread described in the title?

If yes, the issue is that to keep compatibility with the 10 Series I need my previous build with CUDA 11.8, but 50 Series requires CUDA 12.8, so i basically need to make two GPU versions...
I could also move to one unified VideOCR version that downloads at the first startup the correct PaddleOCR version depending on your hardware. But that would require the most amount of work and comes also with a few other implications.
I think I will go for the first variant, cause I don't have the time and interest right now to switch everything to a modular approach.

**Comment by techguru0** [comment]
> > might need to make a modified version of paddle for your program
> 
> [@techguru0](https://github.com/techguru0) What are you referring to? The main issue of this thread described in the title?
> 
yea I figured it was the cuda version
I wonder if ZLUDA would be useful here

**Comment by timminator** [comment]
I've now made a new v1.3.2 release. You can find it here:
https://github.com/timminator/VideOCR/releases/tag/v1.3.2

You will see that there is now a version specifically for 10 Series graphics cards and 16-50 Series graphics cards. This version should now again work correctly for you here.

Please try it out and report back if it works for you.
